### ISSUE TITLE
Go To Definition

### ISSUE THREAD

**Issue by tingerrr** [typst/webapp-issues#125]
### Description

VS Code offers `Ctrl + LMB`, which takes you to the definition by default. A feature like this would be great for the typst web app.

For built-ins this could send you to the docs (with a popup asking if you want to open a new tab),  (see also: typst/webapp-issues#124).
For packages, this could link to the [typst/packages](../../packages) entry (once again with a popup) as the version, path and line numbers are known by the compiler.

### Use Case

In more complex documents with lots of helper functions or even just checking the docs of a built-in function, having a fast way to be led directly to the definition or documentation would increase productivity.

**Comment by Andrew15-5** [comment]
In Vim mode, this should be triggered with `gd`.

**Comment by Andrew15-5** [comment]
This has been available for quite a while (I only found out about this now):

![image](https://github.com/user-attachments/assets/5a9314f0-4938-4e27-aa22-780b930aaf26)

It's the section at the home page of the web app.

But it's still missing the `gd` feature in the Vim mode, plus I think it should be mentioned in the changelog.

**Comment by Andrew15-5** [comment]
@laurmaedje, can you please comment on the Vim mode situation? Do I create a separate issue?

**Comment by laurmaedje** [comment]
You can open an issue though I‘m not sure we‘ll realistically get to it soon.

**Comment by Andrew15-5** [comment]
I'm not talking about soon, I'm talking about it not being forgotten (because you silently closed the issue despite `gd` not being implemented). Now it definitely won't be: https://github.com/typst/webapp-issues/issues/451.

**Comment by laurmaedje** [comment]
I did that because the feature itself is there. There’s always something to improve and you couldn’t ever really close a feature request as broad as this one otherwise. If there are things left to do that people care about, they will open a new issue anyway. As you just proved. ;)

**Comment by Andrew15-5** [comment]
True and factual. But since I mentioned the Vim mode almost a year ago, I would appreciate it if you at least would've said "open an issue for that". The closed issue without any comment whatsoever was perceived negatively as it kinda implied that you ignored the Vim part. The perceived emotion might've been due to the amount of care for the Vim mode. I do think that you might be just super busy, but there was no comment an hour after closure (normally the comment is written upon closing an issue).

**Comment by laurmaedje** [comment]
You're right, I should've responded to that in some way upon closing.
