### ISSUE TITLE
Webapp project file corruption detection

### ISSUE THREAD

**Issue by moinsr** [typst/webapp-issues#130]
### Description

After the server outage from 09.08.2023 one of our projects was corrupted.
We only got weird error messages from the compiler that could not find our bibliography citation labels.

We tried duplicating the Project, but it failed due to a 'corrupted file'.

We fixed our problem by downloading the backup zip from the first project, creating a new project, and inserting the backup zip's contents.
Everything worked immediately.

So something with syncing failed, I guess. Maybe it would be useful to do a corruption check on compiler errors. 😄  

The reproduction URL points to the corrupted project.

### Reproduction URL

https://typst.app/project/pJ4gdLG29pxtoHv5a5pu3-

### Browsers

Chrome

### OS

Windows

**Comment by reknih** [comment]
We are always working on making Typst more reliable. We suspect that there was an error during project duplication which was since improved. I will close this issue in favour of our ongoing improvements.
