### ISSUE TITLE
Jump to PDF functionality

### ISSUE THREAD

**Issue by LaurenzV** [typst/webapp-issues#143]
### Description

There already is a feature that allows you to click somewhere in the preview and it leads you to where it is in the source code, which is very useful! However, having the opposite would be great as well, e.g. given that you are somewhere in the code, it would be great if there were some functionality that briefly highlights the position in the preview panel.

### Use Case

It makes it easier to find where certain parts of the code are located in the actual output.

**Comment by Fabioni** [comment]
For me, I sometimes just want to jump at the corresponding place in the PDF. Right now, I am typing some random letters and immediately delete them, but this does not feel like a good user experience.

**Comment by laurmaedje** [comment]
There is now a button for this in the menu bar.
