### ISSUE TITLE
Stacktraces for Errors

### ISSUE THREAD

**Issue by ParadaCarleton** [typst/webapp-issues#152]
### Description

I'd love to have a stacktrace for errors (or at least the first few levels), so I can see where in my code things went wrong.

### Use Case

Right now it's almost impossible to debug errors if an exception is thrown inside a library; this should make it much easier to find where my code's going wrong.

**Comment by ensko** [comment]
> Stack traces are typically shown with blue squiggles in the web app

This doesn't work when errors originate in packages, then a trace in the error view would indeed be useful.

Example:
```typ
#import "@preview/oxifmt:1.0.0": strfmt

// "User John has 10 apples."
#strfmt("User {} has {} apples.", "John", /*10*/)
```

The file and line within oxifmt is not visible. Granted, making that information useful without being familiar with Typst's package ecosystem might require a few more user interface changes.

Does this still fit this issue, or should it go in a new one/is there a different one I missed?

**Comment by laurmaedje** [comment]
We do have fairly concrete plans in this area and an issue would likely not really impact them, but if you want you can open one.
