### ISSUE TITLE
Typeface "Inter" is missing italics

### ISSUE THREAD

**Issue by genericusername3** [typst/webapp-issues#166]
### Description

When using the web app to write a document, the typeface Inter does not provide italics even though there are italic font variants.

Maybe this is related to Google Fonts listing Inter as nine separate weights with no oblique variants, although Inter is actually a variable font that defines weight and slant as separate axes. As such, it should be able to provide italics for functions like `emph`

### Reproduction URL

https://typst.app/project/rtK5d78zM8nS7QeWEN5dGA

**Comment by laurmaedje** [comment]
We intentionally curated our own font list rather than just having all of Google fonts. We just downloaded some of the fonts from there. Good to know that there are often differences to the upstream repositories.

**Comment by PgBiel** [comment]
Just ran into the same issue; the solution was to download the Inter font directly from <https://github.com/rsms/inter/releases/>. Seems like there was a new release in November 2023 as well (Inter 4.0), and the README claims Google Fonts is outdated. Perhaps the webapp could just switch to the Inter 4.0 release from GitHub?
