### ISSUE TITLE
Make downloaded file name be the document title name

### ISSUE THREAD

**Issue by SUPERCILEX** [typst/webapp-issues#167]
### Description

Currently when you download a rendered file, the title is the name of the project. However, I sometimes have mostly unrelated files in the same project, each with different titles (e.g. "Class A Homework" and "Class B Homework"). It probably makes more sense to have the downloaded file name be equal to the document title.

### Use Case

Then again maybe not, I'm not 100% sold on this idea.

**Comment by Fabioni** [comment]
It is really strange that this is not the case. I have two documents in one project, and when I download them, I get the same file name twice, even though they are different documents.
It would be even better to select the file name programmatically.

**Comment by Kaduo** [comment]
The best option for my personal use case would be a prompt asking me how I want to name the file and where I want to save it on my computer. I wouldn't mind if it was a setting that would need to be enabled, in case the current behavior is preferred by some users.

**Comment by laurmaedje** [comment]
I think the file name doesn't really make sense because the file name will often be "main.typ". You can write multiple documents in one project, but it's not really the primary use case. I'll close this in favor of the more general https://github.com/typst/webapp-issues/issues/339.
