### ISSUE TITLE
Reconnecting in webapp resets cursor position to start

### ISSUE THREAD

**Issue by jakobhellermann** [typst/webapp-issues#178]
### Description

When you temporarily lose internet connection and regain it later, typst will automatically reconnect and work as expected.
However, the reconnect will reset the cursor position to 0:0.

Reproduction in Firefox:
1. open a typst document
2. move the cursor into the middle
3. Press Alt and enable `File -> Work Offline`
4. Disable `Work Offline`

Typst will display the "Connection Restored" toast and reset the cursor to the beginning.

### Browsers

Firefox

### OS

Linux

**Comment by Fabioni** [comment]
I have always had the problem that the web app constantly reconnects even when the internet connection is working. But that hasn't been a problem so far. With the bug described above, however, it is very annoying.  It usually happens when I switch tabs and then go back to Typst.

**Comment by laurmaedje** [comment]
@jakobhellermann Can you still reproduce this? We weren't able to.

**Comment by Fabioni** [comment]
Still have this problem. I worked with a bad internet connection today, and it was almost unusable because of that. It does not always jump to the beginning of the file, I think it only happens when the connection is lost AND the browser tab is not focused.
