### ISSUE TITLE
Browser cache in bad state causes loading project timeout

### ISSUE THREAD

**Issue by emosy** [typst/webapp-issues#181]
### Description

I'm not sure how to reproduce this problem, but this probably happened because I was refreshing the page often to fix #177. If you refresh the page often and do it while it's still loading, this may cause it.

When I would go to typst.app, it would work fine and show me my projects. When trying to open a project, it would stay loading for a long time, then eventually tell me it timed out and the server wasn't working. I don't remember the exact error message (and it takes a long time to get it to show up again), but it would be nice to at least have it recommend clearing the browser cache or trying from an incognito tab.

I was able to work around this issue by first testing from an incognito tab (which confirmed that the webapp was still working) and then by using Chrome's "Empty Cache and Hard Reload" feature from the developer menu, which also fixed it in my non-incognito tab.

I am using Chrome 118.0.5993.89 (Official Build) (64-bit) (cohort: Stable) on Windows 11 Version 22H2.

### Browsers

Chrome

### OS

Windows

**Comment by laurmaedje** [comment]
Since we've changed a lot about the infrastructure since this issue was opened and haven't heard similar reports, I'll close this issue.
