### ISSUE TITLE
Client-side encryption for projects

### ISSUE THREAD

**Issue by miliog** [typst/webapp-issues#182]
### Description

It would be very neat if you could encrypt your projects inside the web app. As I understand it, the compilation already happens client-side, so it should be possible. Of course that may complicate team workspaces and you may lose access to your project if you ever forget your current password, so it should be a toggleable setting (per project, user or team) and a backup passphrase would probably help as well. The specifics of that feature and its implementation should be carefully considered.

### Use Case

- Much better privacy because the server admin can't read the actual content of the stored projects
- Adds an additional layer of protection against data breaches
- Tbh I wouldn't mind if it was an exclusive feature for paying customers. So that would definitely be a benefit for your company as it adds another good reason to do business with you ;)

**Comment by kothavade** [comment]
If I see a company offer encryption as a paid feature the implication is that the free version isn't private, which leaves a bad taste in my mouth--personally at least, I feel that paid features in an open-core model should be enhancements, not something as basic as a guarantee that your data is private. Basically, I think that eventually transparent encryption would be great, but selling it as a feature and making it opt-in seems not great)

**Comment by laurmaedje** [comment]
Proton Docs now implemented something like this and I [quote](<https://www.techradar.com/computing/cyber-security/google-docs-look-outtheres-a-new-private-alternative-in-town>)

> Building collaborative documents that retain E2EE was very difficult, and not something that we've seen anyone else doing on the market
> 
> The biggest challenges seem to have been key exchange and synchronized key information, the ability to invite people to collaborate, revoke those permissions, and share documents privately. 

This quote coming from a company built completely around security illustrates how technically challenging this feature would be. It's simply not something that is feasible for us to implement in the foreseeable future.
