### ISSUE TITLE
Clicking in the preview results in "No file selected" instead of jumping to the right code location 

### ISSUE THREAD

**Issue by Fabioni** [typst/webapp-issues#186]
### Description

The preview/code sync does not work anymore if I am not already in the right .typ file.
It used to work jumping between #include files.

### Browsers

Chrome

### OS

macOS

**Comment by laurmaedje** [comment]
Are you sure the bug is still present? I fixed it yesterday. 🤔

**Comment by Fabioni** [comment]
Indeed. After reloading, it is fixed.
