### ISSUE TITLE
Compiler version Typst 0.8.0 is not 0.8.0

### ISSUE THREAD

**Issue by MDLC01** [typst/webapp-issues#187]
### Description

When selecting "Typst 0.8.0" as the compiler version, the compiler that is used is not actually v0.8.0 (seems to be v0.6.0).

This can be seen because the following file does not compile on the web app with "Typst 0.8.0" as the compiler version, but it compiles when using [the GitHub release](https://github.com/typst/typst/releases/tag/v0.8.0).

```typ
#figure.caption
```

I was able to confirm that:
- compiler version "Typst 0.9.0" is strictly greater than v0.8.0,
- compiler version "Typst 0.7.0" is strictly between v0.6.0 and v0.8.0, and
- compiler version "Typst 0.6.0" is strictly less than v0.7.0.

**Comment by laurmaedje** [comment]
You are totally right, 0.8 turned into 0.6 at the point 0.9 went live because of a merge slipup in the file that defines the available versions. Really sorry about that, it is fixed now.
