### ISSUE TITLE
Typst projects do not load in Edge if 'Enhance your security on the web' is on

### ISSUE THREAD

**Issue by gldraphael** [typst/webapp-issues#191]
### Description

Projects do not load in Edge depending on the security configuration.

```
pJmdIaVAlTyG7Sv0gRxZQz:74  ReferenceError: settings is not defined
    at pJmdIaVAlTyG7Sv0gRxZQz:72:19
(anonymous) @ pJmdIaVAlTyG7Sv0gRxZQz:74
worker-e1615df6.js:2  [2] RuntimeError: memory access out of bounds
k @ worker-e1615df6.js:2
worker-e1615df6.js:2  [3] RuntimeError: memory access out of bounds
k @ worker-e1615df6.js:2
```

![image](https://github.com/typst/webapp-issues/assets/10794213/75322b62-4be4-4868-b0d4-6c34516cd390)

**Steps to reproduce:**

In Microsoft Edge,

1. Go to [Settings &rarr; Privacy](edge://settings/privacy)
2. Scroll down to the security section and turn "Enhance your security on the web" **on**. (This is on by default)
3. Now try to load a project, and it will show the above error.
4. Go back to settings and turn "Enhance your security on the web" **off**. 
5. Load the project again, and it should load as expected.

![image](https://github.com/typst/webapp-issues/assets/10794213/b53fe7fe-011f-4e2a-8e84-da3726481a2e)

Link: https://support.microsoft.com/en-us/microsoft-edge/enhance-your-security-on-the-web-with-microsoft-edge-b8199f13-b21b-4a08-a806-daed31a1929d

### Browsers

Microsoft Edge

### OS

Windows

**Comment by laurmaedje** [comment]
Thanks a lot! This explains why the problem went away for some people after some time. They were likely on Balanced mode and Edge started to consider Typst a frequently visited website.

**Comment by reknih** [comment]
We added a warning to the loading screen that triggers for Edge users and shows them how to allow-list Typst. We will pursue this as a bug with Microsoft.

**Comment by laurmaedje** [comment]
Nothing we can do about this, but for people that are affected, the app will outline steps to fix it. So I'll close this.
