### ISSUE TITLE
Download button for all uploaded files

### ISSUE THREAD

**Issue by zouharvi** [typst/webapp-issues#193]
### Description

Downloading uploaded files is only available for non-textual files (e.g. PNG) from this toolbar. Specifically it could also be available for all other file types.
![image](https://github.com/typst/webapp-issues/assets/7661193/26663d3d-3507-44a5-b5d7-f2f84e43597a)

Additionally the context menu could have a "Download" button which would download the file.
![image](https://github.com/typst/webapp-issues/assets/7661193/bd1147cf-2929-4003-ad9e-60218cfa8988)

### Use Case

I'm accessing the web app from multiple computers and usually iterate on the SVG illustrations. Because it's not possible to directly download SVG files, I have to open a text editor locally and copy&paste the SVG content into the file.
While viable, this feels hacky.

**Comment by reknih** [comment]
We'll start by adding a download button to the context menu for all files.
