### ISSUE TITLE
Copying referral link to clipboard not working

### ISSUE THREAD

**Issue by kovar** [typst/webapp-issues#195]
### Description

Copying the spread the word link to clipboard is not working for me on Safari Version 17.0 (19616.1.27.211.1) on macOS Sonoma 14.0 (see below)

https://github.com/typst/webapp-issues/assets/72451476/14900bf3-0b2a-41eb-b5b1-17461b90a9b9

Could be a permissions issue maybe? Not a big deal, I can recommend Typst in other ways ☺️ Thanks for your efforts! 🙏 

### Browsers

Safari

### OS

macOS

**Comment by reknih** [comment]
We have fixed this issue, thank you for reporting!
