### ISSUE TITLE
Support for live BibTeX file

### ISSUE THREAD

**Issue by StarlightScribe** [typst/webapp-issues#199]
### Description

Overleaf allows you to import a remotely hosted BibTeX file, such as from Paperpile. This keeps the bibliography automatically updated as you add references.

### Use Case

This is very important for my workflow, as academic work involves research and writing at the same time. Having to download and upload a new bib file everytime I add a paper to my library simply isn't practical for something like a literature review.

**Comment by Fabioni** [comment]
Same as what I just described here: https://github.com/typst/webapp-issues/issues/4#issuecomment-1806866488

I also see this as a major problem in my workflow right now.

**Comment by oskar2517** [comment]
Alternatively (or additionally), the [File System API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_API) could be used to automatically reload a bib file from the local device.

**Comment by StarlightScribe** [comment]
> Alternatively (or additionally), the [File System API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_API) could be used to automatically reload a bib file from the local device.

This would be a good first step, but ideally as a web app it would be able to pull a remote bib file.

**Comment by laurmaedje** [comment]
This is implemented for Zotero and Mendeley and available in [Typst Pro](https://typst.app/pricing/).

**Comment by danieltomasz** [comment]
How I can use this feature with  Typst Pro? I cannot find a way how to add new references to web-app

**Comment by laurmaedje** [comment]
Responded in the other issue: https://github.com/typst/webapp-issues/issues/4#issuecomment-2319129852

**Comment by laurmaedje** [comment]
No, not currently.
