### ISSUE TITLE
Loading project forever

### ISSUE THREAD

**Issue by fengyuli-dev** [typst/webapp-issues#2]
<img width="395" alt="image" src="https://user-images.githubusercontent.com/76980494/227050832-aefca43e-7aa5-4547-9723-6775de8f6d55.png">

I always get stuck on this page. No way to really use your product!

**Comment by BeteixZ** [comment]
Same here...

**Comment by laurmaedje** [comment]
@BeteixZ could you tell me which browser your using and show me the contents of the web console and network tab?

**Comment by BeteixZ** [comment]
> @BeteixZ could you tell me which browser your using and show me the contents of the web console and network tab?

I'm using Edge 119.0.2151.30 (release) stable, beta channel (x64), here's the screenshot.

![Snipaste_2023-10-28_23-16-04](https://github.com/typst/webapp-issues/assets/17287792/6e78d898-891c-4cdd-9436-45e117add892)

After multiple refresh it still not finish loading.

**Comment by laurmaedje** [comment]
Thanks for the details. As far as I know, this is an Edge-only bug. We'll look into it, in the meantime you can use a different browser.

**Comment by BeteixZ** [comment]
> Thanks for the details. As far as I know, this is an Edge-only bug. We'll look into it, in the meantime you can use a different browser.

Oh, that's surprising to know, and switching to Chrome works. Thanks!

**Comment by laurmaedje** [comment]
@BeteixZ I downloaded that exact build of Edge for Windows and wasn't able to reproduce the problem. Another user also reported problems with that version of Edge yesterday, but it works now for them (for whatever reason). Does the problem happen for all of your projects, even an empty one?

**Comment by BeteixZ** [comment]
> @BeteixZ I downloaded that exact build of Edge for Windows and wasn't able to reproduce the problem. Another user also reported problems with that version of Edge yesterday, but it works now for them (for whatever reason). Does the problem happen for all of your projects, even an empty one?

Yes, it happens on all my projects (and even new created empty one).
Update: Now I can load all my projects on Edge, I did nothing and it just works now.

**Comment by laurmaedje** [comment]
Very strange, the whole thing.

**Comment by BeteixZ** [comment]
Will try tomorrow to see if it happens again.

**Comment by xyspg** [comment]
I am getting this error on both Safari and Chrome. The console.logs are the same. 
<img width="1570" alt="Screenshot 2023-12-15 at 23 06 22" src="https://github.com/typst/webapp-issues/assets/42668274/e6aeb697-64bb-48de-aefd-dccbca512635">

**Comment by kinten108101** [comment]
Same issue. This is happening on my browser which is GNOME Web (Epiphany)

![Chụp màn hình từ 2024-05-26 01-23-38](https://github.com/typst/webapp-issues/assets/55516702/8241eeb0-fd2f-4670-a062-b6dd7209bc52)

**Comment by aditya-singhvi** [comment]
This seems to be happening again on both Chrome and Safari for me

**Comment by Ethan-Chin** [comment]
> This seems to be happening again on both Chrome and Safari for me

same issue here :(

**Comment by axodentally** [comment]
same for me, using Firefox 134.0 and ungoogled chromium Version 131.0.6778.204.

Error: `Uncaught (in promise) CompileError: WebAssembly.compileStreaming(): expected magic word 00 61 73 6d, found cf ff ff 7f @+0`

**Comment by SarvaniK-26** [comment]
Having the same issue on both chrome and safari

**Comment by Mengda-Li** [comment]
Same issue on chrome and safari for mac and android. Even cannot download data file which is really annoying when you have an important meeting

**Comment by X1X1010** [comment]
Same issue. Still endless loading yet

**Comment by reknih** [comment]
Hey, we have fixed an issue at 8:45 AM CET. If the issue persists, please refresh, use another browser, or open a private browsing tab. We would like to apologize for any inconvenience caused.

**Comment by patricorgi** [comment]
Seems that this issue starts happening again...
