### ISSUE TITLE
Browser stuck in a loop continuously flipping between two pages

### ISSUE THREAD

**Issue by HeMuling** [typst/webapp-issues#208]
### Description

**Behavior:**
The browser is stuck in a loop, continuously flipping between two pages and not settling on either, making it impossible to interact or login on the intended page.

**Environment:**
- Browser : Safari
- Browser Version: Version 17.1 (19616.2.9.11.7)
- Operating System:14.1.1 (23B81)

**Possible cause:**
I suspect this can be caused by me using Safari's 'add to dock' function. 

**Description:**
the browser is  flipping between these two pages:
- https://typst.app
- https://api.typst.app/v1/auth/logout?redirect=https://typst.app, with notification: 'Failed to initialize: You must sign in to continue.'

16 hours ago I have encountered this situation, when I first open typst from my dock, I encounter this situation. When I tried to use 'file-open in safari' in typst dock, this situation spread to my Safari. Luckily the Safari somehow repaired itself: after few minutes of looping, typst went back to 'https://typst.app' and allowed me to login again.

However, this time I first open a document is typst from dock, the document is not responding (maybe related to network, happened before), so I open typst on Safari and login. Then the situation happens again. When I tried to force quit typst from dock and reopen, it shows _'Typst can't open the page "https://typst.app/. The error is： "FetchEvent.respondWith
received an error: AbortError: Fetch is aborted" （WebKitServiceWorker:0）'_

While this happened on Safari, typst on Google Chrome is still working

### Browsers

Safari

### OS

macOS

**Comment by reknih** [comment]
We deployed a new service worker. Is the issue fixed for you?

**Comment by HeMuling** [comment]
> We deployed a new service worker. Is the issue fixed for you?

Yes, the issue is perfectly fixed for me. Thanks for helping. I shall close this issue.
