### ISSUE TITLE
typing dead keys like `^2` in web app does not update error messages

### ISSUE THREAD

**Issue by jakobhellermann** [typst/webapp-issues#21]
When typing `$x^2` in the web app editor, the document shows `x²` as expected but in the editor panel there's a stale `"expected expression"` error message on the `^`:

![image](https://user-images.githubusercontent.com/22177966/233442424-b05efefe-924c-41af-ba69-715d068e67d8.png)
  
For context, the events sent by javascript are
```cs
keydown { target: div.cm-content.cm-lineWrapping, key: "Dead", charCode: 0, keyCode: 160 }

keydown { target: div.cm-content.cm-lineWrapping, key: "^2", charCode: 0, keyCode: 50 }
keypress { target: div.cm-content.cm-lineWrapping, key: "^", charCode: 94, keyCode: 0 }
keypress { target: div.cm-content.cm-lineWrapping, key: "2", charCode: 50, keyCode: 0 }
```

**Comment by laurmaedje** [comment]
Should be fixed.
