### ISSUE TITLE
Add auto-theme mode

### ISSUE THREAD

**Issue by komape** [typst/webapp-issues#216]
### Description

Currently, the Typst web app has a light and a dark mode. My laptop has them as well and switches automatically between them based on the time of the day. Many apps and web pages switch then automatically too.

It would be great if the Typst web app would be able to do so as well. Use the OS (or web browsers) theme mode and switch if they switch.

### Use Case

Screen brightness depends on the surrounding brightness. That's why my laptop changes it automatically. Doing this manually is annoying over time.

**Comment by StarlightScribe** [comment]
Should be a simple addition, there's an example here
https://davidwalsh.name/detect-system-theme-preference-change-using-javascript

**Comment by laurmaedje** [comment]
We've implemented this.
