### ISSUE TITLE
Add an option to hide page numbering on the first page

### ISSUE THREAD

**Issue by Andrew15-5** [typst/webapp-issues#218]
### Description

Somewhere over here:
![image](https://github.com/typst/webapp-issues/assets/37143421/b65e5e41-f93f-412d-bbf2-4bdd0c903631)

### Use Case

If a document has some sort of title page, then there is a good chance that no page number must be present on this page. And I think there are plenty of situations where this is the case, so it can be very useful, especially if Typst user isn't familiar with Typst/programming that much (using `locate` inside `set page(footer)`).

**Comment by Andrew15-5** [comment]
I personally used this:

```typ
#let template(doc) = {
  set page(
    footer: locate(
      loc => {
        let page-number = counter(page).at(loc).first()
        let match-list = query(selector(<turn-on-page-numbering>).before(loc), loc)
        if match-list == () { return none }
        align(center, str(page-number))
      },
    ),
  )
  doc
}
```

because I can just slap  `<turn-on-page-numbering>` to a section, which is on the page, where page numbering must start. Usually there is a title page of some sort and then there is an `#outline()` page, but the numbering must start after these pages, i.e., usually the first visible page number is 3 (on the 3rd page).

**Comment by Roald87** [comment]
For people who've never used a template like me: use `#show: template` to activate the template.

**Comment by laurmaedje** [comment]
We don't currently have plans to continue developing the template creation wizard, so I'll close this.

**Comment by Andrew15-5** [comment]
...And if there will be plans in doing that in the future? Will you re-open it?

**Comment by laurmaedje** [comment]
The template creation wizard was sort of the pre-Universe templating story. Now that we have Typst Universe, I don't think we'll continue investing into that.

**Comment by Andrew15-5** [comment]
Yeah, I understand that. But if the wizard isn't going anywhere, then some people who use it will definitely want it to be more flexible. Finding the correct template will be much harder than flipping a few toggle etc. in the GUI. You can't (I think) easily and quickly know if the given template has numbering except for the 1st page.

P.S. I personally don't care, since I'm not the target user for the wizard (at least not anymore) in general.

**Comment by Andrew15-5** [comment]
(Me to the wizard:)
![image](https://github.com/user-attachments/assets/45c2b3b5-fda4-4d40-92f0-13b2fe70e047)
