### ISSUE TITLE
Auto-scroll when collaborators are writing

### ISSUE THREAD

**Issue by Fewrick** [typst/webapp-issues#221]
### Description

The bug happens when I'm working with others on a project. If any member starts writing, the preview auto-scrolls to the current location I'm writing at in the project. 
This is particularly annoying when in the process of reading the document while someone else is editing it. 

### Browsers

Firefox

### OS

Linux

**Comment by laurmaedje** [comment]
Duplicate of https://github.com/typst/webapp-issues/issues/98
