### ISSUE TITLE
Option to rename images automatically on naming conflict

### ISSUE THREAD

**Issue by RuyiLi** [typst/webapp-issues#223]
### Description

When uploading a file with a duplicate name, this popup shows up:

![image](https://github.com/typst/webapp-issues/assets/16544254/f2690157-d5bb-4dfb-b3da-4d13213f274c)

It would be helpful to have a third button (e.g. "Rename") that would automatically append some discriminator such like (1) to the end of the file name, similar to how Windows handles it.

### Use Case

I am using typst for writing notes, and occasionally I need to screenshot a diagram from my textbook. However, all of the screenshots are named "image.png", and so every time I paste a screenshot into the editor there is a naming conflict.

**Comment by xalbd** [comment]
Will address this with a modal on paste, as discussed in #168.
