### ISSUE TITLE
Reload loop when going directly to https://typst.app after signing out

### ISSUE THREAD

**Issue by wpkelso** [typst/webapp-issues#224]
### Description

If one signs out of typst.app after being previously signed in, then tries to access the cached [https://typst.app](url) page directly, it falls into an automatic-reload loop, rather than going to the sign-in screen or the home page.

### Browsers

Firefox

### OS

Linux

**Comment by laurmaedje** [comment]
Can't reproduce this anymore, but we've also changed a lot since this. So I'll close this.
