### ISSUE TITLE
Git Integration

### ISSUE THREAD

**Issue by misskacie** [typst/webapp-issues#226]
### Description

As mentioned in this issue, it would be nice to have typst files be able to be synced through to a github repository automatically.
https://github.com/typst/webapp-issues/issues/86
In regards to the github backups mentioned in the above issue it probably be good to implement it as typst will send a commit if enough changes are made to the documents,  or at a set interval if changes have been made e.g every 24 hours.

I would like to add a further suggestion to also implement it so that commits by users to the github repository can also be synced back into the web interface.

### Use Case

This would make the github integration more useful as it means a team of people working on a typst document are able to use both the typst website and local typst document editing if they want to. Local document editing has the convenience of speed and offline use, while the website is very convenient for working in a team but often slow. Additionally it would make it easier for changes from offline to merged to the online 'production' .

**Comment by nikhilweee** [comment]
This would be a really nice addition. The convenience of opening the website to work on a project is amazing. Adding GitHub integration would provide a safer way to store changes and make sure that data is not lost.

**Comment by hadim** [comment]
I would also love to be able to sync with a GH repo. This is a blocker for me at the moment to switch from overleaf.

**Comment by danieltomasz** [comment]
Indeed, Typst with sync (pull/push) to GH (even as a feature for pro subscribers) could become an alternative to Overleaf, without it  is really hard to decide for me to switch (the commit could be manual decision plus merging pulled changes if other collaborators work locally)

**Comment by oameye** [comment]
Same here!

**Comment by pinpox** [comment]
Alternatively a desktop client, e.g. using electron, so that we can use local Git and open a repository directory locally in the client

**Comment by Ownezx** [comment]
I would also love a git synchronisation as I always prefer having all my work locally.

**Comment by hadim** [comment]
I just figured out that sync with github or gitlab is now possible from the web app since the 29 of July update. It works well for me.

**Comment by cristobaltapia** [comment]
I also just realized this. Very nice! Will it be also possible to sync with a local repository in your computer? That way one would be able to `git clone ...typst_repo` and then `git push`. I guess that it should be possible if you already have the integration with github and gitlab.

**Comment by laurmaedje** [comment]
The repository is not hosted on typst.app. The app only pushes to a remote repository. So you need either GitLab or GitHub in the picture.

**Comment by danieltomasz** [comment]
For others who might be interested, the current implementation has some problem with pulling changes for me https://github.com/typst/webapp-issues/issues/429, other people who are using typst-web with git, do you have the same problem?
