### ISSUE TITLE
Cannot open the web app

### ISSUE THREAD

**Issue by water-mizuu** [typst/webapp-issues#228]
### Description

As of now, the app is just looping an error, stating "Failed to initialize: You must sign in to continue."

### Reproduction URL

https://typst.app/

### Browsers

Microsoft Edge

### OS

Windows

**Comment by geetmankar** [comment]
I have exactly the same issue (MS Edge on Windows), here are the logs for the same:

[chromewebdata-1703418042533.log](https://github.com/typst/webapp-issues/files/13761650/chromewebdata-1703418042533.log)

**Comment by laurmaedje** [comment]
I believe this was a temporary problem. If someone still has something like this, let me know.
