### ISSUE TITLE
Strange behavior where spaces are inserted while typing

### ISSUE THREAD

**Issue by Enivex** [typst/webapp-issues#235]
### Description

Unfortunately I do not know how to reproduce it, but I do have a clip of it happening

https://github.com/typst/webapp-issues/assets/2191754/2ddf5f5f-641d-44bf-b365-4707a780ad42

### Browsers

Firefox

### OS

Windows

**Comment by laurmaedje** [comment]
Most probably this had the same cause as #230, which we've [identified and fixed since](https://github.com/typst/webapp-issues/issues/230#issuecomment-1858495550). I'm going to close this to, but if you still experience this, please tell us.
