### ISSUE TITLE
Conversion from TeX in WebApp using pandoc

### ISSUE THREAD

**Issue by 9SMTM6** [typst/webapp-issues#238]
### Description

Hey there, I just wanted to highlight that I've tried both the conversion support for TeX in the WebApp, and converison using pandoc, and while both are not at all perfect, and usually need touchups, in my experience pandoc is a lot better at it. The typst it generates also isnt what I would write if i would be translating stuff, but it gets most of the basics right, to be a massive help eg. when I get worksheet templates in TeX I can copy most of the tasks.

Since i did not find a discussion of how this was developed and whether pandoc was considered, I wanted to bring this tool to your attention.

If it was considered and did not hold up feel free to immediately close this. Pandoc is licensed under the GPLv2 AFAICT, so I dont actually know if this would be an issue if you offer that in your Webapp, I don't have experience with that kind of application of copyleft work. Also its in Haskell, so its probably never going to be offline capable (?).

### Use Case

A better (still far from perfect expecially when it comes to global layout) conversion of TeX Code to Typst.

**Comment by reknih** [comment]
Hey! Are you using plain TeX or ConTeXt? We actually use Pandoc behind the scenes and pick the LaTeX reader for all files with a .tex MIME Type / extension. If your file wasn't LaTeX but one of the format mentioned above, that could be the source of the problem.

**Comment by 9SMTM6** [comment]
Ah, nvm. Its LaTeX so thats not the issue, the issue is (mostly) behind the screen. 

I thought I was testing it properly and copying in the text of an included preamble, but turns out I uploaded the wrong file.

Thus would be a small improvement btw. As it stands, the WebApp only allows to upload a single TeX file. When I use pandoc on the commandline, it works with included TeX files just fine (as long as they're in the right spot of course). I don't know if one can actually upload folders in the web, so this might not be possible to solve in the general case where one might have a folder structure. But with a hint about about the need to include additional files, and that it only works in the 'flat' case, this might make the web-app simpler to use.
