### ISSUE TITLE
Local Font Access API

### ISSUE THREAD

**Issue by latin-1** [typst/webapp-issues#241]
### Description

https://developer.mozilla.org/en-US/docs/Web/API/Local_Font_Access_API

### Use Case

Thus we can use local fonts without uploading them.

**Comment by GroophyLifefor** [comment]
Browser compatibility seems not flexible enough. Othervise, good idea.

**Comment by Enivex** [comment]
There is no actual standard yet, only a draft that only Chromium supports

https://wicg.github.io/local-font-access/

**Comment by t-rapp** [comment]
I think using local fonts is fine as a fall-back mechanism. When accessing the web service from different client computers, or when working on documents in a collaborative way this could be problematic, though. The look of exported documents will vary depending on the fonts locally available at the client.

My preference would be to have some possibility to store fonts with my user account or team.

**Comment by laurmaedje** [comment]
The combination of this being only a Chromium draft and the fact that is severy hurts reproducibility means we're not likely to pursue this.
