### ISSUE TITLE
Remove "only for experienced users" warning in settings

### ISSUE THREAD

**Issue by basings** [typst/webapp-issues#243]
### Description

The settings state

> Applies keybindings as known from Vi/vim editors. Only for experienced users!

where "only for experienced users" tells me that I shall learn vim keybindings to become an experienced user and as long as I don't do that, I'm not experienced.

### Use Case

Users should not think that vim keybindings are neccessary to master (the) typst (webapp).

**Comment by Enivex** [comment]
Experienced users of Vim, not typst

**Comment by basings** [comment]
Meaning, it's discouraged for beginners in vim?

**Comment by Enivex** [comment]
> Meaning, it's discouraged for beginners in vim?

There has to be some sort of warning there to prevent users from being confused when keys don't work as they expect. If you're familiar with vim, then you're able to make an informed judgement.

**Comment by basings** [comment]
Meaning, it's in an alpha/beta/whatever state and a vim beginner shall not use it because there might be hickups only experienced users know how to handle.

I expect a vim beginner to be educated enough to know how to handle bugs. A warning that it might be buggy would be better than to exclude vim beginners.

**Comment by Heinenen** [comment]
Typst is also meant for people that are not programmers and the like, thus normally do not know what Vim is. The warning is to prevent such a user from enabling that option "on accident" without knowing what it actually does.

**Comment by basings** [comment]
To me the warning reads as if vim keybindings are for experienced typst users. This is why I opened the issue in the first place.

**Comment by basings** [comment]
Thank you @Andrew15-5 that sounds more understabdable to me. Maybe linking to `[Vim](https://github.com/vim/vim)?

**Comment by Andrew15-5** [comment]
> Maybe linking to [Vim](https://github.com/vim/vim)?

You know what? I think that's a great idea! But I was thinking more of a https://en.wikipedia.org/wiki/Vim_(text_editor) or https://www.vim.org/about.php. Because users that don't know what Vim is will probably want to see Wikipedia-like information to easily understand "what's vim?". I think if a person doesn't know what Vim is, there is a high change of not knowing what GitHub/git(-repository) is as well, so linking to repository wouldn't make any difference (in terms of clarity of the Vim term).

**Comment by laurmaedje** [comment]
I have removed the warning completely. It's not that difficult to turn it off if things are weird after turning it on. I haven't added a link because I think (a) people that know Vim don't need a link, (b) people that don't know Vim don't need the setting and will just ignore it anyway.
