### ISSUE TITLE
Add tabs in the cm editor

### ISSUE THREAD

**Issue by cristian-5** [typst/webapp-issues#248]
### Description

We need support for a setting that allows us to choose tabs vs spaces (`indentWithTabs: boolean`) inside the codemirror editor of the webapp as well as tab size (`tabSize: integer`).

https://codemirror.net/5/doc/manual.html#option_tabSize

### Use Case

`#freeTheTabUsers`

**We can add the options in the _Editing experience_ section:**

<img width="248" alt="Screenshot 2023-12-29 at 10 28 52 AM" src="https://github.com/typst/webapp-issues/assets/30161685/1dacac6e-dc1a-4058-ac84-515b9e241f06">

**Comment by laurmaedje** [comment]
Closing in favor of https://github.com/typst/webapp-issues/issues/348 which has a bit more details.
