### ISSUE TITLE
Add git/pijul/revision control system access to web app

### ISSUE THREAD

**Issue by jorsn** [typst/webapp-issues#25]
### Description

It would be really helpful to have the files in a project accessible via git/[pijul](https://pijul.com/)/revision control systems.
Overleaf supports git access, but only in the commercial version.

### Use Case

Users could work offline properly and do collaborative real-time editing sessions.
They could also work smoothly in teams with different editing preferences.
Users could set, e.g., git tags to access and compare versions at different stages of the publication process, while still getting the benefits of collaborative real-time editing without installing anything.

### See also

Change bars support: https://github.com/typst/webapp-issues/issues/1

**Comment by laurmaedje** [comment]
Git integration is available in [Typst Pro](https://typst.app/pricing).
