### ISSUE TITLE
Line breaks inconsistent between webapp and local compiler

### ISSUE THREAD

**Issue by linuxrider** [typst/webapp-issues#253]
### Description

With justification enabled, text font set to `Source Sans Pro` and `lang: "de"` there are line breaks for `Terme` and `Termx` in the webapp whereas these are not present for the local compiler.

https://github.com/johannes-wolf/cetz/issues/438

### Reproduction URL

https://typst.app/project/rruDTTFJ1AkCuKO4sXQdsE

### Browsers

Firefox, Chrome

### OS

Windows, Linux

**Comment by laurmaedje** [comment]
I looked at https://github.com/johannes-wolf/cetz/issues/438 and I think the problem is not web app vs local compiler, but more that the reproduce it locally, Source Sans Pro needs to be installed.
