### ISSUE TITLE
Incorrect "Cyclic import" error

### ISSUE THREAD

**Issue by sevesalm** [typst/webapp-issues#254]
### Description

Typst Webapp gives an incorrect `Cyclic import` error in some cases. 

## How to reproduce:

1. Start a new project
2. Rename the initial file to `conf.typ` (and leave it empty)
3. Create a new file and name it `main.typ`
4. Select `main.typ`
5. Paste `#import "conf.typ"` into the file
6. See the error `Cyclic import line 1`

You can switch the preview selector between the files. The error appears when `main.typ` is being previewed.

### Browsers

Chrome

### OS

macOS

**Comment by emilyyyylime** [comment]
(As an aside: it's `#import`, not `@import`)
This seems to go away after a reload

**Comment by sevesalm** [comment]
>(As an aside: it's #import, not @import)

Yes, it was a typo in the bug report, now fixed. Tested with the correct symbol 👍🏼  Reload indeed helps and does not happen locally.
