### ISSUE TITLE
Add Rename Image Option to Upload Conflict

### ISSUE THREAD

**Issue by Aevyz** [typst/webapp-issues#256]
### Description

Add the ability to choose a new name, if the current name is already existing.

![image](https://github.com/typst/webapp-issues/assets/17731961/694a4ead-3f2a-4129-8b2e-2196d60c8661)

### Use Case

Windows names their screenshots `image.png`. This means if I want to upload two screenshots, I need to either rename the previous image in Typst and all references first, or save the image in Windows with a new name. Both are rather frustrating and it would be simpler in my opinion to add a field to this window.

**Comment by laurmaedje** [comment]
Duplicate of https://github.com/typst/webapp-issues/issues/223
