### ISSUE TITLE
Ability to non-persistently modify and preview changes made with Vim mode delete/paste commands in the read-only shared document

### ISSUE THREAD

**Issue by Andrew15-5** [typst/webapp-issues#258]
### Description

I've opened a read-only document that was shared and thought if I can at all change it. Surprisingly I can! But only with delete/cut/paste command in Vim mode, anything else doesn't work (including undo command). There is an error about not being able to change-change stuff, but the preview panel shows what was changed. It's better to remove this ability, so that no one can change anything in any way.

![image](https://github.com/typst/webapp-issues/assets/37143421/dc91f97d-a8f3-48dc-8717-6f8c0fe853de)
![image](https://github.com/typst/webapp-issues/assets/37143421/88600ed5-3b0e-4da2-9980-1c2fa4b25c80)

Update:
The changes persist! I just refreshed the page with intention to clear my "even doings", but they are still there! Even disabling caching and pressing Ctrl+F5 — doesn't work. The question is, how can I clear my "unpersistently-persistent" changes? The answer is to delete the respective entry in the Indexed DB.

### Browsers

Firefox

### OS

Linux

**Comment by laurmaedje** [comment]
As discussed on Discord, the changes aren't synced to the server (because of no permission), but still persisted locally in the browser's IndexDB. While it's thus not a security issue, it's still a bug that should be fixed with priority.
