### ISSUE TITLE
Ability to upload archives or folders

### ISSUE THREAD

**Issue by XcantloadX** [typst/webapp-issues#260]
### Description

Currently you can backup the whole project as a zip file but there's no way to upload it back.

### Use Case

* Restore project backup
* Upload attachments more conveniently

**Comment by laurmaedje** [comment]
We've added support for uploading folders to the editor. This means you now can unpack the backup and drag all of its contents into a new project.

**Comment by Andrew15-5** [comment]
When will this be available?
![image](https://github.com/user-attachments/assets/50dbe68d-0455-4235-a39e-ad77fa349e42)
