### ISSUE TITLE
SVGs get corrupted

### ISSUE THREAD

**Issue by humtn** [typst/webapp-issues#264]
### Description

Hi all,

Whenever I use the online editor and upload a pdf (generated from draw.io desktop app, for instance), it gets converted to a svg as Typst doesnt support pdf (iirc this functionality wasnt there couple months ago, so that's great you've implemented it!),

But, whenever I refresh my browser (closing and relaunching on Firefox), I systematically get: "Failed to parse SVG (unknown token at 1:1) " error on every figure that has been converted and sourced in the typ file.

### Browsers

Firefox

### OS

Linux

**Comment by weltauseis** [comment]
Hi ! I can confirm this happens to me too, on two different projects. For one of those projects, the PDF had been converted manually, so I'm not sure this has anything to do with automatic PDF conversion.

Firefox Developper Edition & Windows.
