### ISSUE TITLE
Make web app free software

### ISSUE THREAD

**Issue by mherrb** [typst/webapp-issues#282]
### Description

Please reconsider you decision to not make the web application freely available. This is the only way a whole new system like typst can be successful. 

### Use Case

- Deployments in organizations that can't use a 3rd party saas, 
- Contribution to new features / bug fixes in the existing application, 
- Making Typst more widely adopted

**Comment by Enivex** [comment]
Regarding your first point:

![Screenshot_20240218_114110_Discord.jpg](https://github.com/typst/webapp-issues/assets/2191754/5bff2912-766b-410c-acc7-f1985114e2af)

For the rest, see the other times this topic has come up.

**Comment by laurmaedje** [comment]
We believe that keeping the web app proprietary is a fair split and a good way to ensure that the Typst project has the funds it needs to grow and sustain itself long-term.

**Comment by mherrb** [comment]
I think you are wrong. Future will tell us.
