### ISSUE TITLE
Transfer project into a team

### ISSUE THREAD

**Issue by apraga** [typst/webapp-issues#283]
### Description

At the moment, the only way to move a project to a team seems to be to download the backup, create a new project in the team and upload all files.

In my use case, there are many pictures in a subfolder so it's a bit cumbersome to do it with #272.

Thanks !

### Use Case

Move projects to a project to share it with the team.

**Comment by laurmaedje** [comment]
You can enter the project, click on the settings in the bottom-left and then select the Team as the project's new owner.

We know that it's a bit hidden and plan to improve that, but the functionality is there.

**Comment by supcik** [comment]
Thank you for this issue. I was also looking for this feature. I changed the settings, but the project did not move. And when I went back to the configuration, the owner was empty :

![image](https://github.com/typst/webapp-issues/assets/30344/de45d9bb-f119-4422-94de-ddc6f41c8976)

Am I missing something ?

**Comment by laurmaedje** [comment]
@supcik That's strange, I cannot reproduce it. Could you send an email to support@typst.app with the project ID (it's in the address bar), so we can investigate?

**Comment by supcik** [comment]
Thank you for your very quick reply. I just had to reload the web page and everything was good.
