### ISSUE TITLE
Expand on characters that automatically enclose a selection

### ISSUE THREAD

**Issue by UnlimitedCookies** [typst/webapp-issues#284]
### Description

Currently, like many IDEs in the Typst webapp you're able to hit `(` and the currently selected text is enclosed in braces `(<text selection>)`. 
So it would be really cool if we could expand this functionality to `*` and `_`. There might also be other keys that this could be used for.

### Use Case

Users that quickly want to make a text bold or underlined for example.

**Comment by laurmaedje** [comment]
Duplicate of https://github.com/typst/webapp-issues/issues/37

**Comment by UnlimitedCookies** [comment]
Sorry bout that. On my preliminary search I couldn't find anything.
