### ISSUE TITLE
Make double click on page bring focus to editor for left/right navigation

### ISSUE THREAD

**Issue by SUPERCILEX** [typst/webapp-issues#285]
### Description

Currently, double clicking on a page to bring the cursor to that location and then using the left right arrow keys goes back and forth between pages which is not what you want. After double clicking the full focus needs to be in the editor so left right arrows aren't captured by the page navigation.

**Comment by Jollywatt** [comment]
I'm surprised this issue hasn't had any more attention — it's a daily annoyance for me.

The description should probably say single-clicking (not double-clicking) as that moves focus to the editor (but left/right still control preview).
