### ISSUE TITLE
Can't load projects in safari (iPadOS)

### ISSUE THREAD

**Issue by JedimasterLu** [typst/webapp-issues#286]
### Description

I encounter the same problem in issue #233. When I try to open my projects, an error occurs. Maybe the memory limits for iOS and iPadOS should be even lower?
<img width="582" alt="image" src="https://github.com/typst/webapp-issues/assets/138737788/70a8f433-3dec-4928-a373-d99078a14aa1">
My system version is 17.3.1.

### Browsers

Safari

### OS

iOS or iPad OS

**Comment by laurmaedje** [comment]
We have tried to fix this issue by automatically detecting how much memory iOS will give us at runtime. Would be good to know whether that resolves the issue for you.

**Comment by JedimasterLu** [comment]
It works!! Thanks for your reply and your brilliant project.
