### ISSUE TITLE
Clicking on sections in the reference is janky

### ISSUE THREAD

**Issue by frozolotl** [typst/webapp-issues#287]
### Description

With the new update that rolled out today, clicking on a previously closed section in the [reference](https://typst.app/docs/reference) will sometimes open all sections in the tree.
I'm not sure exactly what is necessary for that to happen.

Additionally, it is jarring to see the elements moving around a lot after each click. 

### Browsers

Firefox

### OS

Linux

**Comment by laurmaedje** [comment]
Are you sure that this new? I don't think we've changed anything about this.

**Comment by frozolotl** [comment]
> Are you sure that this is new? I don't think we've changed anything about this.

I definitely did not notice this before.
