### ISSUE TITLE
Add Comment Functionality Similar to Overleaf in Typst Editor Pane

### ISSUE THREAD

**Issue by HakonHarnes** [typst/webapp-issues#29]
### Description

Currently, Typst.app doesn't have a comment feature similar to Overleaf, where users can leave comments in the editor pane for collaborative purposes. This feature would be beneficial for users who work in teams or with supervisors who leave feedback directly within the document. Adding this functionality would encourage more users to migrate from other platforms to Typst for their document editing needs.

![screenshot](https://user-images.githubusercontent.com/89907156/234906104-c6f78742-c60d-4ae6-94e6-d151b7e45b21.png)

### Use Case

Student is working on their thesis and wants to use Typst for writing and editing the document. Their supervisor is used to leaving comments within the document in Overleaf. By incorporating a comment feature similar to Overleaf, the student can easily migrate to Typst, allowing for efficient collaboration and feedback.

**Comment by linuxrider** [comment]
I wish the feature could be even better as that of Overleaf.
The comments in Overleaf are not reflected in the source code on export.
This prevents working in a mixed online and offline/local scenario.

**Comment by theowiik** [comment]
This is a must-have for me! Are there any plans for this?

**Comment by laurmaedje** [comment]
Yes, it's planned, but it will still take a bit of time.

**Comment by Carlvebbesen** [comment]
Any update on this?

**Comment by laurmaedje** [comment]
It is currently being worked on, but since it's a complex feature, I can't yet say when it will be ready.

**Comment by JakobTopholt** [comment]
Appreciate it @laurmaedje, you're doing God's work.

**Comment by laurmaedje** [comment]
We forgot to close this but it's available in Typst Pro and On-Premises since a while.
