### ISSUE TITLE
Cannot import packages from online database due to TypeError: NetworkError when attempting to fetch resource.

### ISSUE THREAD

**Issue by coder3112** [typst/webapp-issues#293]
### Description

When trying to import a package from the online package database, the following error happens:
`failed to download package (TypeError: NetworkError when attempting to fetch resource.)`
## Minimal Reproducible Example
```
#import "@preview/cetz:0.2.1"
= This does not compile
```
This problem is only present on firefox, same code compiles on Chromium based browsers without issue.
## CORS
I think this is an issue with CORS, due to the following error in the web console:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://packages.typst.org/preview/cetz-0.2.1.tar.gz. (Reason: CORS request did not succeed). Status code: (null).`

### Browsers

Firefox

### OS

Windows

**Comment by coder3112** [comment]
It works now? Did not do anything.

**Comment by edgarogh** [comment]
I have the same issue in Firefox right now with cetz

**Comment by laurmaedje** [comment]
@edgarogh Could send send a screenshot of the browser console from the dev tools when this happens? 

We had a few cases like this and some were related to specific browser extensions.

**Comment by edgarogh** [comment]
Yes, I'm sorry for the false alarm, I forgot to disable a dev extension that had set an X-Forwarded-For HTTP header. Your reverse proxy might deny incoming requests with this header set, for good reasons.

Sorry for the noise in this busy issue tracker, I should've checked better 😞
Maybe this will still help somebody, should anyone end up in the exact same situation as me.
