### ISSUE TITLE
A double forward slash in some links (docs)

### ISSUE THREAD

**Issue by Andrew15-5** [typst/webapp-issues#296]
https://staging.typst.app/docs/reference/introspection/location//#locatable
The link probably shouldn't have two slashes back to back, because you can also do https://staging.typst.app/docs/reference/introspection/location///////#locatable, but because you can, doesn't mean you should.

https://staging.typst.app/docs/reference/introspection/here/:

![image](https://github.com/typst/webapp-issues/assets/37143421/79e0b1b0-c7db-409f-8cb4-652369eb946a)

**Comment by MDLC01** [comment]
I think this should be on the main repo, because the link is computed here: https://github.com/typst/typst/blob/a2d097686f01b2834f4a9b313bd9c1c692210479/docs/src/link.rs

But it doesn't matter too much anyway.

**Comment by Andrew15-5** [comment]
I don't know where the links are being created, and a few other reasons why I posted it here.
