### ISSUE TITLE
Typst Universe category gradients cause slowdown in Firefox

### ISSUE THREAD

**Issue by kojq** [typst/webapp-issues#309]
### Description

flex container for categories causes browser (especially Firefox) to slow down.

https://typst.app/universe/

### Reproduction URL

https://typst.app/universe/

### Browsers

Firefox, Chrome

### OS

Linux

**Comment by reknih** [comment]
It's actually the gradient background that's slow in Firefox. I have disabled it in that browser using a CSS feature query.
