### ISSUE TITLE
Pass file name to system inputs to allow control flow of imports.

### ISSUE THREAD

**Issue by fizykz** [typst/webapp-issues#316]
### Description

When rendering a file, pass a variable to the `--input` of Typst with the file name (and it's directory) so that it may be accessed with `sys.inputs` in the code.

One line change:
```bash
typst --input main=fileToBeRendered.typ       . . .
```

### Use Case

This simple change allows control flow based on the file being rendered.  This is especially useful for large projects, which may be split into several chapters but that you may wish to have more control over while simultaneously saving performance in such a situation.  Thanks to sillyfreak on Discord for coming up with this solution.

```rust
if sys.inputs == "main.typ" {
  // Yay control flow!
}
```

**Comment by TheJanzap** [comment]
Please re-file this issue in the https://github.com/typst/typst repo, as it's a complier feature request, not specifically a web app one

**Comment by laurmaedje** [comment]
Closing in favor of https://github.com/typst/webapp-issues/issues/391

**Comment by laurmaedje** [comment]
(Always passing the input file name automatically, specifically in the web app, would be somewhat strange.) But supporting inputs at all is definitely in scope for the web app.
