### ISSUE TITLE
Popup preview is totally broken

### ISSUE THREAD

**Issue by SUPERCILEX** [typst/webapp-issues#317]
### Description

Probably the same as https://github.com/typst/webapp-issues/issues/246, but for me pages show up but they're blurry (as in haven't re-rendered) and then when I edit something the entire document appears twice. Also zooming in or out does nothing.

**Comment by laurmaedje** [comment]
For such a bug report, it would be crucial to know your browser and OS.

**Comment by SUPERCILEX** [comment]
Ok, I figured out the simplest way to reproduce (happens on multiple computers, so probs not OS dependent). Create a new blank document and type in `#lorem(100)`. Then open the popup preview. Seems to have something to do with typing stuff before opening the preview.

If you can't repro, I can try to get a list of computers this bug repros on for me.

**Comment by laurmaedje** [comment]
I can't reproduce it in any of Chrome/Firefox/Safari on macOS.

**Comment by SUPERCILEX** [comment]
Huh, well that's unfortunate. I'm on `Chrome 123.0.6312.105 (Official Build) (64-bit)`, `Linux pop-os 6.8.0-76060800daily20240311-generic #202403110203~1711393930~22.04~331756a SMP PREEMPT_DYNAMIC Mon M x86_64 x86_64 x86_64 GNU/Linux`. The other person this happens to is on a chromebook, so maybe this is a linux specific bug.

**Comment by SUPERCILEX** [comment]
Seems to have been fixed by https://github.com/typst/webapp-issues/issues/246.
