### ISSUE TITLE
Jumbled Text on Project Reload

### ISSUE THREAD

**Issue by rohitanwar** [typst/webapp-issues#326]
### Description

Opened a project after few hours only to find the content got jumbled up. The following types of "text errors" happened

1. Some parts of the text got removed like quotation marks and some extra letters got added
2. Lines I had previously deleted reappeared. Lines I added after that didn't go away so this doesn't seem like a save issue?
3. Parts of the text got duplicated.
4. Similar error to #310 

The project is shared between multiple people but no one had accessed it when it happened. Also I took a backup before I closed the site and the backup was completely fine. Can taking backup cause this as I just closed the web app a few seconds after the backup downloaded? 

I tried looking it up but it doesn't seem like this has been reported before. 

Also this happened on a Chromebook so I am mentioning Linux as my OS

### Browsers

Chrome

### OS

Linux

**Comment by JoeHCQ1** [comment]
I ran into this today, here's a screenshot of it:

![image](https://github.com/typst/webapp-issues/assets/49208786/dcdcc4d5-f897-4155-b6f5-11fe3ec2509c)

Our workaround was to re-paste in the text from our local copy - it'd have been interesting to copy out the malformed text to see what it looked like. Oh well, it's gone now.

Note, it did this on my computer first, then after my co-worker refreshed a few times he had the same problem. Before that, he could still render the doc.

**Comment by laurmaedje** [comment]
First of all: I'm very sorry for the inconvenience and also for the delayed response (we were on vacation). This is all very strange and I hope we can get it sorted out quickly.

> Can taking backup cause this as I just closed the web app a few seconds after the backup downloaded?

Taking a backup can definitely not cause this, as it does not touch the collaboration data structures at all, only a read-only copy of it.

@rohitanwar What would be really helpful is to have the actual garbled and ungarbled text. Do you happen to still have that? If you have already overwritten it, we can also take a look at the cloud snapshots. For that I would need the project ID from the address bar and your permission to look into the project (you can also send the ID to privately to hello@typst.app).

> Similar error to #310

There were multiple things going on in #310 (the weird file name and then the bad state), which error exactly did you get?
