### ISSUE TITLE
Preview when switching between available completions

### ISSUE THREAD

**Issue by asmarcz** [typst/webapp-issues#330]
### Description

Display a re-rendered document/part of a document when selecting from a completion popup.

### Use Case

When citing I found I'd prefer a shorter variant and I would like to see how the different citing styles would render. Now, I have to choose each one individually before seeing the result, which is time consuming.

![image](https://github.com/typst/webapp-issues/assets/18113532/c24abbcb-d03b-4886-bd6f-680b05124e75)

**Comment by laurmaedje** [comment]
Duplicate of https://github.com/typst/webapp-issues/issues/184
