### ISSUE TITLE
Share link should not end with special char

### ISSUE THREAD

**Issue by adrfantini** [typst/webapp-issues#335]
### Description

I was testing some things and the app returned a share link such as [this one](https://typst.app/project/r7sTBcR9S9IrJHqnzDvsC_).

However, if a share link contains a trailing special char, such as in this case (it ends in _), some systems, such as github, will not properly recognise it:
https://typst.app/project/r7sTBcR9S9IrJHqnzDvsC_ (notice missing trailing `_`)

In general I would think that it's best to keep to alphanumeric chars for share IDs

### Reproduction URL

https://typst.app/project/r7sTBcR9S9IrJHqnzDvsC_

### Browsers

Chrome

### OS

Linux

**Comment by reknih** [comment]
New share links will only include alphanumeric characters.
