### ISSUE TITLE
Change log for the web app

### ISSUE THREAD

**Issue by TheJanzap** [typst/webapp-issues#340]
### Description

I'd like to see a change log or a news feed for the changes to the web app where I can read up on what's new instead of just randomly stumbling over new features that have been added. This would also been useful to see if certain bugs have been fixed.

### Use Case

I was unaware that spell checking had been added until I randomly spotted it in the project settings. If the web app had a changelog, I would have easily found out that way. I think it would also be beneficial to announce big new features to attract new users.

**Comment by laurmaedje** [comment]
The web app has gained a news feed at the right side of the dashboard a while ago, where we announce larger changes.
