### ISSUE TITLE
Use custom template from webapp

### ISSUE THREAD

**Issue by zhc7** [typst/webapp-issues#350]
### Description

I would like to create a template on the web app and use it for future projects. I know I can publish the template as a package or use it locally, but is it possible to treat a project on the web app as a template, so that I can directly choose the template I made on the web app when using "Start from template"?

### Use Case

This feature would be useful when I want to create a template for myself conveniently.

**Comment by laurmaedje** [comment]
We're currently working on adding support for private packages and templates. These features will become part of our paid subscription, Typst Pro, which will launch soon.

**Comment by zhc7** [comment]
ok, thanks for replying.
