### ISSUE TITLE
Cannot search for module in documentation

### ISSUE THREAD

**Issue by MDLC01** [typst/webapp-issues#353]
### Description

Searching for "sys" or "system" in the documentation does not suggest [the System page](https://typst.app/docs/reference/foundations/sys). Similarly, searching for "calc" or "calcultion" does not suggest [the Calculation page](https://typst.app/docs/reference/foundations/calc).

### Reproduction URL

https://typst.app/docs

**Comment by Andrew15-5** [comment]
I think this is a duplicate of https://github.com/typst/typst/issues/8271.
