### ISSUE TITLE
Members of team can change document ownership

### ISSUE THREAD

**Issue by LowkeyCoding** [typst/webapp-issues#357]
### Description

When in a team, all users with the member role can change the owner of a document, this removes the access to it from the rest of the team. The behavior I would expect is that only the administrator would be able to do it. 

### Browsers

Firefox

**Comment by laurmaedje** [comment]
In principle, this is working as intended. Team members can create, delete, and duplicate projects, which is in combination equivalent to being able to change the owner.

**Comment by LowkeyCoding** [comment]
It felt odd, but I can see the point that members are inherently trusted and, therefore, "hopefully" will not intentionally remove access from other members.
