### ISSUE TITLE
Add the Bitstream Charter font

### ISSUE THREAD

**Issue by TheColorDarkBlue** [typst/webapp-issues#363]
### Description

Requesting [Bitstream Charter](https://en.wikipedia.org/wiki/Bitstream_Charter) to be added to the default font list. Charter is a popular serif font created by Matthew Carter in 1987 (also the creator of Georgia for Microsoft). 

Charter is also the official font Google Deepmind uses for their publications. For example: [Learning Agile Soccer Skills for a Bipedal Robot with Deep Reinforcement Learning](https://arxiv.org/pdf/2304.13653).

### Use Case

Users can use Charter without having to upload `.ttf` or `.otf` files into their project.

### Links to Font Files

- [https://practicaltypography.com/charter.html](https://practicaltypography.com/charter.html)
- [https://github.com/davidseegert/Bitstream-Charter](https://github.com/davidseegert/Bitstream-Charter)

### License

>This is a copy of the Charter fonts which Bitstream contributed to the X consortium. This is the original notice included with the fonts:

>(c) Copyright 1989-1992, Bitstream Inc., Cambridge, MA. You are hereby granted permission under all Bitstream propriety rights to use, copy, modify, sublicense, sell, and redistribute the 4 Bitstream Charter (r) Type 1 outline fonts and the 4 Courier Type 1 outline fonts for any purpose and without restriction; provided, that this notice is left intact on all copies of such fonts and that Bitstream’s trademark is acknowledged as shown below on all unmodified copies of the 4 Charter Type 1 fonts. BITSTREAM CHARTER is a registered trademark of Bitstream Inc.

### LaTeX Packages For Reference

- Charter: [Font Catalogue](https://www.tug.org/FontCatalogue/charterbt/), [CTAN](https://ctan.org/pkg/charter)
- XCharter: [Font Catalogue](https://www.tug.org/FontCatalogue/xcharter/), [CTAN](https://ctan.org/pkg/xcharter)

**Comment by Enivex** [comment]
I'm not sure automatic type 1 conversions are good enough to be included in the web app. You can always upload your own fonts to the project if you really need that precise font.

**Comment by 1991CRX** [comment]
> I'm not sure automatic type 1 conversions are good enough to be included in the web app. 

Hi @Enivex, could you explain what you mean by this in greater detail? Thank you.

**Comment by Enivex** [comment]
> > I'm not sure automatic type 1 conversions are good enough to be included in the web app. 
> 
> Hi @Enivex, could you explain what you mean by this in greater detail? Thank you.

Bitstream is an old Type 1 font, and the repository you linked is an automated conversion to an opentype font.

**Comment by Enivex** [comment]
> > Bitstream is an old Type 1 font, and the repository you linked is an automated conversion to an opentype font.
> 
> Are all the default fonts in the web app OpenType? 
> 
> 

Yes, Type 1 fonts are deprecated, and pretty much only supported by LaTeX

**Comment by Enivex** [comment]
> > > > Bitstream is an old Type 1 font, and the repository you linked is an automated conversion to an opentype font.
> > > 
> > > 
> > > Are all the default fonts in the web app OpenType?
> > 
> > Yes, Type 1 fonts are deprecated, and pretty much only supported by LaTeX
> 
> Thanks. Why wouldn't automatic Type 1 -> OpenType conversions be good enough to be included in the web app?

I'm not saying they necessarily are, but typically they're not. Usually you're better off picking a different native font.

(Regardless, I do not have any influence over font inclusion in the web app)

**Comment by laurmaedje** [comment]
Bitstream Charter only supports the Windows Latin-1 codepage minus the € symbol. It might make more sense to include Charis SIL instead, which has a far wider character set, though it also has some design modifications. See also the page you linked: https://practicaltypography.com/charter.html
