### ISSUE TITLE
Reverse the preview colors in dark mode

### ISSUE THREAD

**Issue by reknih** [typst/webapp-issues#38]
### Description

In dark mode, there shall be an option to invert the colors of the preview.

### Use Case

This would prevent eye strain.

**Comment by CapitaineToinon** [comment]
Is there any way of doing the same when using the opensource typst cli? I doubt I could do something that detects system theme but at least a function I could wrap the document with would be nice

**Comment by laurmaedje** [comment]
The easiest way would probably be to use a PDF viewer that has this feature. I think there are some.

**Comment by ruffsl** [comment]
Is there a way to invert the color space for a typst document via a few statements that could be commented out as needed?

This sort of works, but I'm not sure it'd be graceful for transpenrt figures and the like:
```typst
#set page(fill: black)
#set text(fill: white)
...
```
