### ISSUE TITLE
Wrong page number while WebApp exporting PDF with custom page ranges

### ISSUE THREAD

**Issue by HeZeBang** [typst/webapp-issues#399]
### Description

When exporting a PDF with custom page ranges, the Table of Contents (TOC) in the PDF displays the complete outline with incorrect page numbers.

Maybe it should be part of the TOC?

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Fixed in Typst 0.12.
