### ISSUE TITLE
Zotero Integration in Web App

### ISSUE THREAD

**Issue by jowch** [typst/webapp-issues#4]
Hi! Typst is a brilliant idea, and the execution is well done. It is likely to be too early to make this suggestion, but here goes. It may be possible to generate a `.bib` file through the Zotero API and use that in a project. That would be amazing!

**Comment by Fabioni** [comment]
I suggest copying the method from Overleaf where you can set a URL of an external file and by pressing a button automatically retrieve the current version. (https://www.overleaf.com/learn/how-to/How_to_upload_a_file_using_an_external_URL)

Right now, I created a shell file on my laptop which loads the bibtex file from zotero web api into clipboard and manually copy it in my bibtex. file in the Typst Webapp. Having the described feature would allow me to just press a button after adding a new paper to Zotero.

**Comment by danieltomasz** [comment]
The pricing page https://arc.net/l/quote/lrjuomgh  say something about ability to pick the connection with synced bib file, I didnt see anything like this when I connect my Zotero account to typst project

**Comment by laurmaedje** [comment]
> I didnt see anything like this when I connect my Zotero account to typst project

You need to create a synced file on a per-project basis via the dropdown next to file and folder buttons in the file side panel.

Step 1:
<img width="258" alt="Bildschirmfoto 2024-08-30 um 00 06 34" src="https://github.com/user-attachments/assets/8bc45910-7513-4663-98e6-abb806968d30">

Step 2:
<img width="700" alt="Bildschirmfoto 2024-08-30 um 00 06 43" src="https://github.com/user-attachments/assets/d33781e0-c0ae-4485-a0d6-fea912d02a99">

We plan to add web app docs in the future to make this more discoverable!

**Comment by danieltomasz** [comment]
Thanks, this is really helpful!
