### ISSUE TITLE
Doesn't load due to outdated HTML

### ISSUE THREAD

**Issue by telotortium** [typst/webapp-issues#403]
### Description

The following CSS is returning an HTTP 404: https://typst.app/assets/index-c9d4bda6.css. This means the front page is completely blank:

<img width="1438" alt="Screenshot 2024-07-20 at 12 10 19" src="https://github.com/user-attachments/assets/0697066a-bec0-400e-b5eb-3574e8aa4d66">

### Reproduction URL

https://typst.app

### Browsers

Chrome

### OS

macOS

**Comment by LaurenzV** [comment]
It works fine for me. Perhaps you could try clearing your browser cache?

**Comment by telotortium** [comment]
@LaurenzV it seems to work on my phone (iOS). I will try again on my laptop later.

**Comment by laurmaedje** [comment]
This was temporary.
