### ISSUE TITLE
Indentation with `tab` key broken after last update

### ISSUE THREAD

**Issue by codeblessing** [typst/webapp-issues#405]
### Description

After latest update to https://typst.app `tab` key is not working as expected.

### Expected behavior

Pressing `tab` inserts whitespace in place of cursor **or** (if text is selected) indentation of every line with selected text is  increased by one step.

### Actual behavior

Pressing `tab` does nothing, neither inserts white space nor increases indentation.

Although not breaking anything, this bug is quite irritating from usability perspective because it's a lot harder now to format code manually.

### Browsers

Firefox

### OS

Linux

**Comment by PgBiel** [comment]
Fixed, thank you!
