### ISSUE TITLE
Github integration fails: "The user was not found"

### ISSUE THREAD

**Issue by GaetanLepage** [typst/webapp-issues#406]
### Description

Hello,

I encounter an issue with the GitHub integration.

![image](https://github.com/user-attachments/assets/47d3e962-ca1b-4373-b3c8-c1f21c9dbb1f)

Here is what I have done:
- Successfully linked my GH profile
- Created a repo from GH
- Pushed once and create a `master` branch.
- Tried to link an existing Typst project to this new repo, (selecting "New branch")

-> I get a popup saying 
```
Cannot connect version control system: The user was not found.
```

**Comment by florianb** [comment]
Same here - let me know if i can provide further information.
