### ISSUE TITLE
Links to SSH repos are broken on Typst Universe

### ISSUE THREAD

**Issue by kothavade** [typst/webapp-issues#410]
### Description

Click on the `Repository: GitHub` link in the about section of the given reproduction URL to see an example.

### Reproduction URL

https://typst.app/universe/package/esotefy

### Browsers

Firefox

### OS

Linux

**Comment by kothavade** [comment]
A potential fix would be a simple regex to match for GitHub SSH links, parse the `repo_owner/repo_name` part out and put that in an HTTP GitHub link instead.

**Comment by laurmaedje** [comment]
As-is, `git@github.com:...` (in the linked package) is missing a URL schema to be a valid URL. But aside from that, I think it's fair to request that links in typst.toml should be browser-navigable links. That's fundamentally more portable than us doing some transformation in the background. I don't really see a good reason to put an ssh link there in the first place.
