### ISSUE TITLE
Web App losing connection immediately after opening project

### ISSUE THREAD

**Issue by cristobaltapia** [typst/webapp-issues#411]
### Description

Today I have been having problems with the web app losing connection right after opening a project. This means that changes are not being saved to the server. I tried Firefox and Chrome under Linux.

### Browsers

Firefox, Chrome

### OS

Linux

**Comment by Tiggax** [comment]
+1 
For me trying on edge has a similar result, while in chrome the complier crashes

**Comment by JuliusJaenchen** [comment]
+1
(MacOS + Chrome)

I first noticed this today; last week, this was not an issue.

**Comment by cristobaltapia** [comment]
Well, now it is working for me again. Should I close this issue?

**Comment by laurmaedje** [comment]
Do any of the involved projects happen to use Zotero Sync?

**Comment by laurmaedje** [comment]
Closing this as it was a temporary server problem.
