### ISSUE TITLE
First-level heading not displayed on Typst Universe

### ISSUE THREAD

**Issue by SkytAsul** [typst/webapp-issues#413]
### Description

On Typst Universe, the first-level headings of the README do not appear (those prefixed by a single #.

For instance, [this package](https://typst.app/universe/package/silky-report-insa/0.2.1/) has multiple first-level headings (see the README [here](https://github.com/typst/packages/blob/main/packages/preview/silky-report-insa/0.2.1/README.md)) and they are not displayed on the Universe page.

### Browsers

Microsoft Edge

### OS

Linux

**Comment by vitto4** [comment]
Yup, I noticed this as well when using an image as `h1`.

[Github](https://github.com/vitto4/ttuile/blob/main/README.md) render | [Universe](https://typst.app/universe/package/ttuile) render

**Comment by laurmaedje** [comment]
Typically, there is just one top-level heading in a Markdown document with the title. Since Typst Universe already displays its own title, we strip this heading.
