### ISSUE TITLE
Use monitor ppi for preview rendering

### ISSUE THREAD

**Issue by EpicEricEE** [typst/webapp-issues#420]
### Description

The preview should use the ppi of the monitor so that a scale of 100% matches the real size, similar to how it works in PDF viewers.

### Use Case

Consistency and makes it easier to visualize the size of things

**Comment by JamesxX** [comment]
I'm always needing to hold up an A4 sheet to my screen to get the zoom right 😭

**Comment by laurmaedje** [comment]
I don't think this is possible. We already factor in the devicePixelRatio, but Monitor PPI do not seem to be available through any Web APIs. See here: https://stackoverflow.com/questions/22861287/get-device-ppi-in-javascript
