### ISSUE TITLE
Grammarly extension doesn't make changes to text

### ISSUE THREAD

**Issue by this-josh** [typst/webapp-issues#421]
### Description

When you select a Grammarly option the underlining goes, and the work is highlighted, but the change doesn't happen

https://github.com/user-attachments/assets/40802ce0-9dc4-4312-8874-ebb633ad52dc

I cannot see any errors in the console, and my Grammarly extension works fine in Overleaf - and this GitHub issue text box. 

### Browsers

Chrome

### OS

macOS

**Comment by Enter-tainer** [comment]
sounds like "grammarly doesnt support typst"

**Comment by this-josh** [comment]
It sounds like it, but I don't believe it is. 

- I know of no other site where this behaviour is exhibited
- The Grammarly error checker and suggestion box are working correctly. It's just the text replacement, which isn't right

Without an error message, it is difficult to know which side the problem is, but given these two points, it seemed like a Typst word replacement issue.

**Comment by laurmaedje** [comment]
See https://github.com/codemirror/dev/issues/1416

**Comment by laurmaedje** [comment]
Given the response by the author of CodeMirror, there is not much we can do. It appears to be an issue with Grammarly.

**Comment by Dherse** [comment]
Actually @laurmaedje, in the latest version of Chrome/typst/Grammarly: it works :)

Edit: I tested this like a week ago and it did not and now it does 🎉

**Comment by KelvinChung2000** [comment]
@Dherse, Hi, which version of Chrome/typst/Grammarly are you using, as this is not working on me on Chrome
