### ISSUE TITLE
[git] changes are pulled  from remote, but the files  aren't changed in webapp - cause overwritting external changes

### ISSUE THREAD

**Issue by danieltomasz** [typst/webapp-issues#429]
### Description

I make the changes in the local repository and pushed the  changes to remote (commit A).
Then withing the webapp  I pulled  succesfully the changes from the remote from github but the files  in the webfolder aren't changed. (the popup was saying that I sucessfully pulled)
I wanted to check if maybe there silent errors/problems with merge/unstashed changes so I commit  and pushed changes from my web app (commit B).
What I saw in my remote, that commit B was after commit A - commit A was pulled into web-app, but for some reason files weren't changed and when I commited from web-app I overwrtitten the changes.

### Reproduction URL

https://typst.app/project/pEqMpdC6Jojay89eLtMNrK

**Comment by laurmaedje** [comment]
We fixed a bug where the data we keep to be able to merge changes without conflicts got into an invalid state. However, this unfortunately doesn't fix existing invalid state. If this bug still occurs for you, you can "heal" it by pushing at least once. If necessary, you can also revert or force push on the git side and then pull again.

**Comment by danieltomasz** [comment]
Thanks, I am happy to see fix that fast 🙂
