### ISSUE TITLE
[git] Typst git pull is not reliable - bib files sometimes  aren't update

### ISSUE THREAD

**Issue by danieltomasz** [typst/webapp-issues#430]
### Description

I've created a small project to share with my collaborators and supervisor. While we've had several successful pulls in the past, we're now experiencing unreliable updates after using git pull.
Specifically, in our most recent pull:

Changes to the .typ file were successfully pulled.
The .bib file weren't, despite being updated in the remote repository.

This partial update caused our compilation to crash, as the .typ file expected content from the updated .bib file that wasn't present locally.
This inconsistent behavior makes it challenging to effectively collaborate on the project

### Reproduction URL

https://typst.app/project/pv_8ZwDKpgBYe4kq23RlXk

**Comment by Enivex** [comment]
I can't open the project, but the most likely explanation is that the bib file is too large. Is this one of the ones with thousands of references in it?

**Comment by danieltomasz** [comment]
No, I created a mini bib with only those items I am using (~30 positions);
Now I manually copied and pasted changes into online version to make it compile, I have orange dot - it means that there is a conflict the typst-web client cannot resolve?
![image](https://github.com/user-attachments/assets/9a15c611-b283-4e11-894f-fd1b9b571b5f)

When I got my problem, before me manually pasting there weren't orange dot ther

**Comment by danieltomasz** [comment]
yellow/organge dot is gone, but the github changes in bib file do not appear when I try to pull them from the repo

**Comment by laurmaedje** [comment]
We've tracked down a bug in the pull logic yesterday. I hope to get a patch deployed soon.

**Comment by laurmaedje** [comment]
Same issue as #429. Copying my response:

We fixed a bug where the data we keep to be able to merge changes without conflicts got into an invalid state. However, this unfortunately doesn't fix existing invalid state. If this bug still occurs for you, you can "heal" it by pushing at least once. If necessary, you can also revert or force push on the git side and then pull again.
