### ISSUE TITLE
[git]  list allowed formats to be synced within webapp or extend the list including sh scrips

### ISSUE THREAD

**Issue by danieltomasz** [typst/webapp-issues#431]
### Description

I try to add my thesis (ported from markdown pandoc) to the typst and pull in the web-app.
Here is my repo:

![image](https://github.com/user-attachments/assets/a3c66056-dc03-44a0-9040-27fe6f586d99)
When I tried  to create new  project from this git repository I got popup about unacceptable file format
Which format is not acceptable? `sh`? I use this as a git hook.

### Use Case

Be more informative what kind of files are allowed/allows for more files.

**Comment by laurmaedje** [comment]
Shell script files should be allowed and work in my testing. In your screenshot, I don't see any file format that would be disallowed. Without access to the repository, it's hard to tell what is going on.

PDF files are disallowed. Do you possibly have a PDF checked into your repo?

**Comment by danieltomasz** [comment]
Thanks for the reply! The repos works now, sorry for unnecessary pinging you (so I will close it )

PDF are disallowed or  just git ignored?  I understand that adding every change in pdf might pollute the repo, but what if user want to manually add on their side a specific pdf (while pdf in general are gitignored)?

**Comment by laurmaedje** [comment]
For UTF-8-decodable text files, we allow everything. For binary files there is an allow-list and that list doesn't include PDF, so it is strictly forbidden. This is not specific to Git integration, it's general to the web app. If you drag a PDF file into the app, it is auto-converted to SVG.

We are considering to allow more or potentially all file formats in the future, but that blocks on some internal things.
