### ISSUE TITLE
Theme sets to light when exiting Presentation mode

### ISSUE THREAD

**Issue by Tiggax** [typst/webapp-issues#433]
### Description

When using the presentation feature, if the web app is in dark theme, the theme will become light, when the presentation finishes/ you exit.

It's annoying, but toggling the theme changes it back.

### Browsers

Firefox

### OS

Linux

**Comment by oplik0** [comment]
Also ran into this in Brave on Windows and wanted to add that it seems to only happen when theme is set to System for me - if I manually set it to Dark it seems to work fine.

**Comment by Tiggax** [comment]
> Also ran into this in Brave on Windows and wanted to add that it seems to only happen when theme is set to System for me - if I manually set it to Dark it seems to work fine.

Oh, I see!
It seems to do the same for me.
