### ISSUE TITLE
Can accept spellchecker suggestions on a read-only document (client-side only)

### ISSUE THREAD

**Issue by emilyyyylime** [typst/webapp-issues#437]
### Description

Any user with the link to a read-only document can accept spelling suggestions in the 'Improve' tab, and they get applied locally and persist in the cache after reloads.

### Browsers

Firefox

**Comment by Enivex** [comment]
Do they actually get applied to the original document?

**Comment by emilyyyylime** [comment]
Thankfully no! That did confuse us at first
