### ISSUE TITLE
Webapp Load Times

### ISSUE THREAD

**Issue by kurt-rhee** [typst/webapp-issues#443]
### Description

References:  https://github.com/typst/webapp-issues/issues/2

I am creating a new bug report, but the underlying cause is the same as the above closed bug report.  I am using firefox browser and the load time to open a project is quite long. 

I'm liking typsts, thank you for the all of the hard work.

### Browsers

Firefox

### OS

Linux

**Comment by laurmaedje** [comment]
Is it slow or stuck?

**Comment by kurt-rhee** [comment]
It is much faster now, perhaps it was a transitory thing just early this morning?

**Comment by laurmaedje** [comment]
There was indeed a problem caused by our cloud provider Microsoft Azure this morning.
