### ISSUE TITLE
Download projcet / folder archive

### ISSUE THREAD

**Issue by emilyyyylime** [typst/webapp-issues#444]
### Description

Allow downloading a folder in a project, or the entire project's files in a common archive format like zip.

### Use Case

Currently downloading projects for local safekeeping is inconvenient and discards file structure. This would solve those issues

**Comment by TheJanzap** [comment]
You can already download the entire project as a ZIP by going to File -> Backup Project. This also keeps the folder structure of the project. Single file download is also supported (right click on file -> Download), but folder download isn't.

**Comment by emilyyyylime** [comment]
Nice. Maybe it should be made available under other menus/names as well because when I saw that option I somehow hadn't made the connection

**Comment by laurmaedje** [comment]
I think File menu makes sense. And there is also the prominent "Backup" button which does the same thing as well. I think it's pretty prominent already.
