### ISSUE TITLE
Show rules mess with the go-to-definition functionality in the web app

### ISSUE THREAD

**Issue by LaurenzV** [typst/webapp-issues#446]
### Description

See the reproduction URL. Try to click for example on `Etiam` in the second sentence, and it will correctly jump back to the corresponding location in the source code.

Now uncomment the show rule and try again, and it will jump to a slightly different location instead.

### Reproduction URL

https://typst.app/project/rkdshblstJ3CQV_ZSOdH3s

**Comment by laurmaedje** [comment]
Duplicate of https://github.com/typst/typst/issues/2854

**Comment by laurmaedje** [comment]
Fwiw, I usually call this "jump from click" or "to-source jump" to distinguish it from the "go to definition" for variables triggered via Ctrl+Click.

**Comment by LaurenzV** [comment]
Ah oops, sorry for the duplicate.

**Comment by laurmaedje** [comment]
No problem.
