### ISSUE TITLE
"The file is not an acceptable format" error when synchronizing with Github

### ISSUE THREAD

**Issue by GiggleLiu** [typst/webapp-issues#447]
### Description

<img width="468" alt="image" src="https://github.com/user-attachments/assets/edbf70f7-404c-4b71-a14b-d8dce8470cd0">

The connection with GitHub frustrates with quite often. In particular, the above error mesage is not helpful at all. I have been fighting with it for hours.

Is there an easier way to sync with local files? It has become a major challenge for me to use the web app.

### Reproduction URL

https://typst.app/project/p35xZzv3OuJ47VFdAk_igg

### Browsers

Chrome

### OS

macOS

**Comment by laurmaedje** [comment]
Yes, this is unfortunate. Right now if there are forbidden files (like PDFs), the clone fails. We are currently working to fix this, so that instead they are just ignored for the purposes of Git sync.

**Comment by GiggleLiu** [comment]
Is it fixed?

**Comment by laurmaedje** [comment]
Should be, yes.
