### ISSUE TITLE
PNG and SVG export do not function correctly at and below Typst version 0.9.0

### ISSUE THREAD

**Issue by frozolotl** [typst/webapp-issues#452]
## Steps

1. Create new Typst Project.
2. Set version to 0.9.0.
3. Export as PNG or SVG.

![error message](https://github.com/user-attachments/assets/b12b3c13-1566-4961-872f-680c53b6f15b)

If the architecture simply doesn't allow such exports anymore, at least the error message should be improved or the given file formats be disabled.

### Browsers

Firefox

### OS

Linux

**Comment by laurmaedje** [comment]
> If the architecture simply doesn't allow such exports anymore

These exports were only added to the web app after 0.9.0 and not backported. We can add a "PNG export is only supported in Typst 0.10 and above" message like for spell check.
