### ISSUE TITLE
Support different types of english (and other languages) for the spell checker

### ISSUE THREAD

**Issue by PKWadsy** [typst/webapp-issues#458]
### Description

I am from New Zealand, where British English is spoken. We have different spellings for words like
- colour
- flavour
- specialise
and more

It would be nice if you could select which version of English to use if the spell checker is enabled.

### Use Case

Users that use British-English would not have to add so many words to their personal dictionaries.

**Comment by laurmaedje** [comment]
You can configure this by adjusting the region of your document:

`#set text(region: "GB")`

Currently supported regions for English are US/GB/AU/CA/ZA.
