### ISSUE TITLE
Can't register.

### ISSUE THREAD

**Issue by Manubi** [typst/webapp-issues#464]
### Description

Wanted to register and after clicking accept TOS I got this:
`{
message: "",
success: "false",
code: [
"SESSION_INVALID"
]
}`

https://api.typst.app/v1/auth/accept-tos

### Browsers

Chrome

### OS

macOS

**Comment by PgBiel** [comment]
Hey, can you confirm you're registering at https://typst.app and not (by accident) at https://staging.typst.app?

**Comment by laurmaedje** [comment]
A second option that could result in this is that you might have already registered a longer time ago and forgot. (Happened to a lot of folks.) The error in that case is not great.

**Comment by Manubi** [comment]
> A second option that could result in this is that you might have already registered a longer time ago and forgot. (Happened to a lot of folks.) The error in that case is not great.

This. Thanks!

And just for your info... I guess almost no one is reading the 3 modals after the login.

**Comment by laurmaedje** [comment]
The original intent was to not leak which accounts exist, but this kind of failed and the result is that it's still possible to see but the UX for registering if you are already registered is _also_ bad. but that's the reason why it doesn't just flat out say "account exists".

**Comment by Manubi** [comment]
Why not just send an email to re/validate your account?

**Comment by laurmaedje** [comment]
Yeah, we can definitely improve this. I just wanted to explain how things ended up in this rather wonky state.
