### ISSUE TITLE
Comment only share-link

### ISSUE THREAD

**Issue by pohlm01** [typst/webapp-issues#465]
### Description

It would be great to have a link to share that does not allow modifying the text, but only placing/answering comments. If the "tracing changes" feature becomes available, it might also be nice to allow editing but force the tracing of changes.

### Use Case

This is helpful to receive feedback while at the same time being sure that nothing can be changed without noticing.

**Comment by laurmaedje** [comment]
Duplicate of https://github.com/typst/webapp-issues/issues/439
