### ISSUE TITLE
NewCM Math Bold font exception not applied

### ISSUE THREAD

**Issue by EpicEricEE** [typst/webapp-issues#481]
### Description

Typst v0.12.0 includes the font exception added with typst/typst#5126, thus the bold math font should be selectable just by increasing the weight. This works correctly in the CLI, but not in the web app, where it is still required to set the font to the unprettified name `"NewComputerModernMath"`.

### Browsers

Chrome

### OS

Windows

**Comment by reknih** [comment]
The web app's font packaging has been updated to Typst 0.12.0, the change should appear tonight.

**Comment by EpicEricEE** [comment]
I can still reproduce this

**Comment by laurmaedje** [comment]
Looks like the font deployment failed. We'll take another look tomorrow.
