### ISSUE TITLE
PDF/A and SVG export don't work on development version

### ISSUE THREAD

**Issue by Aaron-Rumpler** [typst/webapp-issues#486]
### Description

When the compiler version is set to "development version", PDF/A and SVG export are disabled.
![PDF/A Export](https://github.com/user-attachments/assets/365c1333-89a9-40da-9589-e7ed3e04f46d)
![SVG Export](https://github.com/user-attachments/assets/14d93fb1-7919-4876-8aa6-dacb011e4df4)

### Browsers

Safari

### OS

macOS

**Comment by laurmaedje** [comment]
ah right, need to adjust the check for those
