### ISSUE TITLE
Linux Libertine → Libertinus Serif

### ISSUE THREAD

**Issue by YDX-2147483647** [typst/webapp-issues#498]
### Description

![Customize a template](https://github.com/user-attachments/assets/5f5503e7-5d76-4b26-a369-447b02e6c2b6)

The default template in the web app is still using Linux Libertine. Just click the button above, choose a title, _Next_, _Next_, and you will get the following warning.

![warning](https://github.com/user-attachments/assets/ca8d76ca-ed49-4446-8a6d-730f8d7565af)

https://github.com/typst/typst/releases/tag/v0.12.0 changes the default font to Libertinus Serif. So I think the web app should follow?

### Reproduction URL

N/A

### Browsers

Firefox

### OS

Windows

**Comment by laurmaedje** [comment]
Good catch. Probably very few people still use this template wizard, but as long as it's there we should update it.

**Comment by YDX-2147483647** [comment]
Additionally, maybe in the future, the wizard should set the font according to the language.
![](https://github.com/user-attachments/assets/71b6c4a6-b6d7-4e5d-8dc9-d256a1ec5876)

Relates to: #48

But for now, I think that might be too far, considering https://github.com/typst/typst/issues/794 and other non-English issues.
