### ISSUE TITLE
"Pop out" Preview

### ISSUE THREAD

**Issue by ParadaCarleton** [typst/webapp-issues#58]
### Description

A button I can push to make the preview "pop up" in its own window.

### Use Case

I have 2 monitors, so it would be neat to be able to turn the preview into a pop-up so I can have it on a different screen while I'm typing.

**Comment by Regenhardt** [comment]
You can create a read-only share link (although write works too, doesn't matter in this case) and open that link in another browser window. Preferably probably one where you're not logged in to avoid interferences. In that second window, set your view to preview only - it'll get updated live too.

Seems this could be kinda automated too by making a smaller version of the web app that just contains the preview window and real time connection, then send a link to that to a new window.

**Comment by laurmaedje** [comment]
This is now implemented.
