### ISSUE TITLE
Publish at flathub as flatpak

### ISSUE THREAD

**Issue by lumingzh** [typst/webapp-issues#67]
### Description

It will be great to publish the app and runtime/compiler as flatpak at flathub.

### Use Case

All linux users can easily install and auto update the app, thank you.

**Comment by ortolot** [comment]
> There is no official local app yet, so there is nothing to publish.

Well, there is the compiler, which could very well be published as a Flatpak on Flathub. That would be much more practical for upgrades than manually downloading the binary.

By the way, the Typst compiler is actually available as a [Snap](https://snapcraft.io/typst), which is advertised in the [Typst Open Source page](https://typst.app/open-source#download).
