### ISSUE TITLE
Spell check in web app

### ISSUE THREAD

**Issue by NeutrinoLiu** [typst/webapp-issues#7]
hey guys, fantastic project with swift editing response. I am wondering can you add spell checking function in your web ui typst.app?

**Comment by tom-ricci** [comment]
What's the status on spell-checking in Typst? I'm a fan of using it for papers however it really defeats the purpose of an efficient text-based editor if I have to copy what I write into another editor that supports spellchecking. The overhead of opening Word or Google Docs and creating a new document and then specifically extracting and copying over the content that should be spellchecked offsets many of the time gains I receive from using Typst.

**Comment by tnjoga** [comment]
are there any updates regarding spell checking in the web app? I'm quite dependent on it when writing papers and my current workflow of having everything checked via another website like @tom-ricci is doing it, is quite time consuming.

**Comment by laurmaedje** [comment]
It's planned to be implemented in Q1 2024.

**Comment by Polydynamical** [comment]
Any updates on this? I've already submitted a research proposal with typos and I feel very sad :(

**Comment by laurmaedje** [comment]
It is being worked on as we speak.

**Comment by Polydynamical** [comment]
Updates? The above research proposal I submitted got REJECTED and I feel a big reason has to do with typos :( :( :( :( :( :(

**Comment by Kreijstal** [comment]
> Updates? A research proposal I wrote with Typst got REJECTED and I feel a big reason has to do with typos :( :( :( :( :( :(
> 
> > It's planned to be implemented in Q1 2024.
> 
> Q1 ended 1 month ago 😮

lmao just do not use the web app? you cannot blame the webapp

**Comment by Jollywatt** [comment]
I was delighted to discover spellchecking in the web app today!
But I was equally horrified to discover that's it's currently impossible to specify a dialect — the dictionary is controlled by `text(lang: "..")`, which can't distinguish between, e.g., US and UK English.
Is there intention to add this flexibility, or is spell check "done"?

**Comment by xalbd** [comment]
> I was delighted to discover spellchecking in the web app today! But I was equally horrified to discover that it's currently impossible to specify a dialect — the dictionary is controlled by `text(lang: "..")`, which can't distinguish between, e.g., US and UK English. Is there intention to add this flexibility, or is spell check "done"?

Try using `region: “…”`! :)

**Comment by Jollywatt** [comment]
> Try using region: “…”! 😃

Eureka! Sorry for not looking at the docs properly!

Maybe the fact that `text.region` is respected can be mentioned in this tool tip (which is what led me here).

<img width="276" alt="Screenshot 2024-05-04 at 11 24 14" src="https://github.com/typst/webapp-issues/assets/24970860/2d0ce140-2da3-45f1-a5da-e2ac2da62d15">
