### ISSUE TITLE
App should provide standard shortcuts for commenting

### ISSUE THREAD

**Issue by ynx0** [typst/webapp-issues#97]
### Description

Currently, shortcuts for commenting are non-standard, at least on a US keyboard layout. Standard shortcuts are <kbd>CommandOrCtrl+/</kbd> and <kbd>CommandOrCtrl+Shift+/</kbd> for line and block comments.

### Use Case

Makes for smoother UX by tapping into existing muscle memory.

**Comment by matj1** [comment]
@laurmaedje Why did you not use Ctrl/Cmd+Shift+/ for block comments? It seems common in many text editors.

BTW, Ctrl+Shift+A opens the list of addons on Firefox.

**Comment by laurmaedje** [comment]
> Why did you not use Ctrl/Cmd+Shift+/ for block comments? It seems common in many text editors.

I didn't see those anywhere. But I'm also on a German keyboard. It's generally kind of hard to figure out shortcuts that work across all browsers, all operating systems, and all keyboard layouts.
